
- title: Privacy
  text: Your security is our top priority. Your personal and financial data are encrypted (even while using your phone) to ensure that it stays safe when you use RedCarpet. We never sell or share your information outside RedCarpet.

- title: Buyer's Guarantee
  text: If you have any problem with the delivery of the order, we will work with our ecommerce partners to fix that for you... or we will refund you the entire cost, as long as the eligibility requirements are met.

- title: 24x7 Protection &amp; Support
  text: We monitor every account and transaction 24X7 to prevent fraud. In the rare event that something does seem suspicious, please email us at support@redcarpet.cash and we will get on top of that. 

- title: Legal compliance 
  text: RedCarpet works with several financial institutions like banks and we make sure that our processes are fully compliant. If your experience has been otherwise, please reach out to us at support@redcarpetup.com and we will figure out what went wrong. 
